version: '3'

services:
  master:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - './data/master:/bitnami'
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=replxx
      - MYSQL_ROOT_PASSWORD=qqxj
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=user1xx
      - MYSQL_DATABASE=repltestdb
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
  slave:
    image: 'bitnami/mysql:latest'
    ports:
      - '${MYSQL_SLAVE_PORT:-3307}:3306'
    restart: always
    # depends_on:
    #   - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=replxx
      - MYSQL_MASTER_HOST=${MYSQL_MASTER_HOST:-218.168.168.150}
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=qqxj
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './data/slave:/bitnami'

# volumes:
#   mysql_master_data:
#     driver: local
